dist: trusty
language: java

jdk: oraclejdk8

script: mvn clean verify

before_install:
  - sudo service mysql stop
  - sudo service postgresql stop
  - sudo service acpid stop
  - sudo service atd stop
  - sudo service cron stop
  - sudo service memcached stop
  - sudo service ntp stop
  - sudo service rabbitmq-server stop
  - sudo service resolvconf stop
  - sudo service sshguard stop
  - sudo service ssh stop
  - sudo service rsyslog stop
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then openssl aes-256-cbc -K $encrypted_9f89ff80bfee_key -iv $encrypted_9f89ff80bfee_iv -in settings-central.tar.enc -out settings-central.tar -d && tar -xf settings-central.tar ; fi

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: if [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then mvn -s ./settings.xml deploy
  -Dexternal -DtrimStackTrace=false; else mvn verify -DtrimStackTrace=false
  -Ddocker.keepRunning; fi

after_failure:
  - docker images
  - docker ps -a
  - docker logs indexer
  - docker logs fcrepo
  - docker logs elasticsearch
  - cd pass-client-integration && mvn docker:stop

after_success:
  - cd pass-client-integration && mvn docker:stop
